//index->首页
//login->登录
//pending->待处理
//allocated->已分配
//--chooseCounselor->选择顾问
//bookManage->预约管理
//orderManage->订单管理
//userManage->用户管理
//--list->列表
//--detail->详情
//--dealRecord->交易记录
//--bookRecord->预约记录
//--followRecord->跟进记录
//--newClient->新增客户
//--newDealRecord->新增交易记录
//--newFollowRecord->新增跟进记录
//settings->系统管理
//--clientLevelSettings->客户等级设置
//--boundStore->绑定门店
//--chooseStore->选择门店
//--staffManage->人员管理
//--staffInfo->人员信息
//logs->日志
//wallet->贝壳钱包
//--incomeAndExpenditure->收支明细
//bankCard
//--bankCardManage->银行卡管理
//--bankCardList->银行卡列表
//--bankCardUnbinding->银行卡详情，解绑
//--bankCardBinding->绑定银行卡
//--withdraw->提现
//--withdrawRecord->提现记录